services:

  streaming-service:
    image: 'oms-streaming-service:latest'
    container_name: oms-streaming-service
    build:
      context: .
    environment:
      KAFKA_BROKERS: broker:29092
      KAFKA_ENABLED: "true"
      CONSUMER_GROUP: streaming-service-group
      SERVER_PORT: 8092
    ports:
      - "8092:8092"   # HTTP
      - "7000:7000"   # RSocket WebSocket
    networks:
      - oms-net
    depends_on:
      - broker

  # Use shared Kafka from oms-core, or define here for standalone testing
  broker:
    image: confluentinc/cp-kafka:7.9.3
    hostname: broker
    container_name: streaming-broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    networks:
      - oms-net

networks:
  oms-net:
    driver: bridge
