spring:
  application:
    name: oms
  config:
    import: optional:file:.env[.properties]
  datasource:
    write:
      url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
      username: ${DB_USER:postgres}
      password: ${DB_PASSWORD:changeme}
      driver-class-name: org.postgresql.Driver
      hikari:
        minimum-idle: 8
        maximum-pool-size: 32
    read:
      url: ${READYSET_URL:jdbc:postgresql://localhost:5433/postgres}
      username: ${DB_USER:postgres}
      password: ${DB_PASSWORD:changeme}
      driver-class-name: org.postgresql.Driver
      hikari:
        minimum-idle: 8
        maximum-pool-size: 32
  threads:
    virtual:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  kafka:
    properties:
      auto.register.schemas: true
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    consumer:
      properties:
        specific.avro.reader: true
        spring.deserializer:
          key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
          value.delegate.class: io.confluent.kafka.serializers.KafkaAvroDeserializer
        schema.registry:
          url: http://localhost:8081
      group-id: orders-group
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      auto-offset-reset: earliest
    producer:
      acks: all
      retries: 3
      properties:
        retry.backoff.ms: 250
        schema.registry:
          url: http://localhost:8081
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

kafka:
  enabled: ${KAFKA_ENABLED:false}
  order-topic: ${ORDER_TOPIC:orders}
  command-topic: ${COMMAND_TOPIC:commands}

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  tracing:
    sampling:
      probability: 0.1

springdoc:
  show-actuator: false
  swagger-ui:
    use-root-path: true

tracing:
  enabled: ${TRACING_ENABLED:false}
  url: ${TRACING_URL:http://localhost:4317}

logging:
  level:
    org.hibernate.SQL: INFO
    org.springframework.transaction: INFO

server:
  port: ${SERVER_PORT:8090}